model_name: deepict_unet3d_ittt

train_batch_size: 8
eval_batch_size: 10
test_batch_size: 12
dataset: deepict_h5

depth: 2
initial_features: 4
encoder_dropout: 0.0
decoder_dropout: 0.1
BN: group_norm
# BN: batch_norm
elu: False

learning_rate: 0.003
base_lr: 0.003
max_lr: 0.003
step_size: 40
decay_milestones: []
decay_gamma: 1.0
weight_decay: 1e-4
max_epochs: 150
grad_clip_norm: null


train_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/12-12-trimmed-256-b20/work/training_data
val_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/12-12-trimmed-256-b20/work/validation_data
test_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/12-12-trimmed-256-b20/work/testing_data/vpp_test
normalize_data: True
