model_name: denoiseg

train_batch_size: 8
eval_batch_size: 1
test_batch_size: 1
dataset: denoiseg
mask_ratio: 0.1
# mask_ratio: 0.7
window_size: 5

depth: 2
initial_features: 4
encoder_dropout: 0.0
decoder_dropout: 0.1
BN: group_norm
elu: False

learning_rate: 0.003
decay_milestones: []
decay_gamma: 1.0
# weight_decay: 1e-4
max_epochs: 1000
grad_clip_norm: null

# train_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/12-12-trimmed-256-b20/work/training_data
# val_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/12-12-trimmed-256-b20/work/validation_data
# test_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/12-12-trimmed-256-b20/work/testing_data/def
# train_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/12-12-trimmed-256-b20/work/testing_data/def_train
# val_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/12-12-trimmed-256-b20/work/testing_data/def_train/030
# train_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/30-01-deepict-norm-256/work/training_data/def_train
# val_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/30-01-deepict-norm-256/work/training_data/def_val
# train_data_root_dir: /media/ssd3/diyor/30-01-deepict-norm-256/work/training_data/def_train
train_data_root_dir: /media/ssd3/diyor/30-01-deepict-norm-256/work/training_data/def_train
val_data_root_dir: /media/ssd3/diyor/30-01-deepict-norm-256/work/training_data/def_val
# test_data_root_dir: /media/ssd3/diyor/23-01-deepict-256-clean/work/training_data/vpp/007
# train_data_root_dir: /media/ssd3/diyor/12-12-trimmed-256-b20/work/testing_data/def_train
# val_data_root_dir: /media/ssd3/diyor/12-12-trimmed-256-b20/work/testing_data/def_val


test_data_root_dir: /media/ssd3/diyor/30-01-deepict-norm-256/work/training_data/def_train
# test_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/30-01-deepict-norm-256/work/training_data/def_train
test_entire_gt: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/VPP/labels/TS_0001_membranes_trimmed.mrc
test_membrain_pred: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/VPP/membrain_out_no_aug/TS_0001_trimmed_MemBrain_seg_v10_alpha.ckpt_segmented.mrc
# test_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/12-12-trimmed-256-b20/work/testing_data/vpp_train/003
# test_data_root_dir: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/training/21-01-rein-256/work/training_data/rein/004

normalize_data: False
