model_name: denoiseg

train_batch_size: 32
eval_batch_size: 32
test_batch_size: 1
dataset: denoiseg_f2fd

depth: 2
initial_features: 4
encoder_dropout: 0.0
decoder_dropout: 0.1
BN: group_norm
elu: False

# F2FD masking
bernoulli_mask_ratio: 0.5
phase_inversion_ratio: 0.1
min_mask_radius: 0.05
max_mask_radius: 0.1
# min_mask_radius: 0.1
# max_mask_radius: 0.2

lambda_ce: 0.2

learning_rate: 0.003

# expLR
gamma_decay: 0.99
max_epochs: 600

train_data_root_dir: /media/ssd3/diyor/patch-160-overlap-80
train_tomo_names:
  # - def/026
  # - def/030
  # - def/034
  - vpp/001
  - vpp/002
  - vpp/004

val_data_root_dir: /media/ssd3/diyor/patch-160-overlap-80
val_tomo_names:
  # - def/037
  - vpp/003
val_gt: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/VPP/labels/TS_0003_membranes_trimmed.mrc

test_data_root_dir: /media/ssd3/diyor/patch-160-overlap-80
# test_tomo_names:
#   - def/034

# test_entire_tomo: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/DEF/tomograms_normalized/TS_034_trimmed.rec
# test_entire_gt: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/DEF/labels/TS_034_membranes_trimmed.mrc
# test_membrain_pred: /mnt/hdd_pool_zion/userdata/diyor/data/deepict/DEF/membrain_out_no_aug/TS_034_trimmed_MemBrain_seg_v10_alpha.ckpt_segmented.mrc
test_tomo_names:
  - rein/005/pixel-13

test_entire_tomo: /mnt/hdd_pool_zion/userdata/diyor/data/in_situ_reinhardtii/tomograms_pixel_13-68/01122021_BrnoKrios_arctis_lam1_pos5.mrc
test_entire_gt: /mnt/hdd_pool_zion/userdata/diyor/data/in_situ_reinhardtii/labels_pixel_13-68/01122021_BrnoKrios_arctis_lam1_pos5_memb1.mrc
test_membrain_pred: /mnt/hdd_pool_zion/userdata/diyor/data/in_situ_reinhardtii/predictions_pixel_13-68/01122021_BrnoKrios_arctis_lam1_pos5_MemBrain_seg_v10_alpha.ckpt_segmented.mrc
# test_tomo_names:
#   - rein/005

# test_entire_tomo: /mnt/hdd_pool_zion/userdata/diyor/data/in_situ_reinhardtii/tomograms/01122021_BrnoKrios_arctis_lam1_pos5.mrc
# test_entire_gt: /mnt/hdd_pool_zion/userdata/diyor/data/in_situ_reinhardtii/labels/01122021_BrnoKrios_arctis_lam1_pos5_memb1.mrc
# test_membrain_pred: /mnt/hdd_pool_zion/userdata/diyor/data/in_situ_reinhardtii/predictions/01122021_BrnoKrios_arctis_lam1_pos5_MemBrain_seg_v10_alpha.ckpt_segmented.mrc
