atty_YTC009_3_lam7_ts2_corrected_patch0_split0_0000.nii.gz
atty_YTC009_3_lam7_ts2_corrected_patch1_split0_0000.nii.gz
atty_YTC009_3_lam8_ts2_corrected_patch0_split0_0000.nii.gz
atty_YTC009_3_lam8_ts2_corrected_patch1_split0_0000.nii.gz


chlamy_50_patch20_split0_0000.nii.gz
chlamy_50_patch21_split0_0000.nii.gz
chlamy_54_patch0_raw_split0_0000.nii.gz
chlamy_54_patch0_split0_0000.nii.gz
chlamy_54_patch1_raw_split0_0000.nii.gz
chlamy_54_patch1_split0_0000.nii.gz
chlamy_54_patch2_raw_split0_0000.nii.gz
chlamy_54_patch2_split0_0000.nii.gz
chlamy_5_patch0_split0_0000.nii.gz
chlamy_633_patch10_raw_split0_0000.nii.gz
chlamy_633_patch10_split0_0000.nii.gz
chlamy_633_patch11_raw_split0_0000.nii.gz
chlamy_633_patch11_split0_0000.nii.gz
chlamy_633_patch12_raw_split0_0000.nii.gz
chlamy_633_patch12_split0_0000.nii.gz
chlamy_640_patch0_split0_0000.nii.gz
chlamy_640_patch1_split0_0000.nii.gz
chlamy_640_patch2_split0_0000.nii.gz
chlamy_6_patch0_split0_0000.nii.gz
chlamy_8_patch0_raw_split0_0000.nii.gz
chlamy_8_patch0_split0_0000.nii.gz
chlamy_8_patch1_raw_split0_0000.nii.gz
chlamy_8_patch1_split0_0000.nii.gz
chlamy_8_patch2_raw_split0_0000.nii.gz
chlamy_8_patch2_split0_0000.nii.gz


cts_patch010_split0_0000.nii.gz
cts_patch011_split0_0000.nii.gz
cts_patch012_split0_0000.nii.gz
cts_patch013_split0_0000.nii.gz
cts_patch014_split0_0000.nii.gz
cts_patch015_split0_0000.nii.gz
cts_patch016_split0_0000.nii.gz
cts_patch017_split0_0000.nii.gz
cts_patch018_split0_0000.nii.gz
cts_patch019_split0_0000.nii.gz


deepict_TS_0007_patch0_raw_split0_0000.nii.gz
deepict_TS_0007_patch1_raw_split0_0000.nii.gz


deepict_TS_034_patch0_raw_split0_0000.nii.gz
deepict_TS_034_patch1_raw_split0_0000.nii.gz
deepict_TS_034_patch2_raw_split0_0000.nii.gz
deepict_TS_034_patch3_raw_split0_0000.nii.gz
deepict_TS_041_patch0_raw_split0_0000.nii.gz
deepict_TS_041_patch1_raw_split0_0000.nii.gz
deepict_TS_041_patch2_raw_split0_0000.nii.gz


hdcr_9_patch0_split0_0000.nii.gz


polnet_patch010_split0_0000.nii.gz
polnet_patch011_split0_0000.nii.gz
polnet_patch012_split0_0000.nii.gz
polnet_patch013_split0_0000.nii.gz
polnet_patch014_split0_0000.nii.gz
polnet_patch015_split0_0000.nii.gz
polnet_patch016_split0_0000.nii.gz
polnet_patch017_split0_0000.nii.gz
polnet_patch018_split0_0000.nii.gz
polnet_patch019_split0_0000.nii.gz


rory_tomo35a_patch0_raw_split0_0000.nii.gz
rory_tomo35a_patch0_raw_v2_split0_0000.nii.gz
rory_tomo35b_patch0_raw_split0_0000.nii.gz
rory_tomo35b_patch0_raw_v2_split0_0000.nii.gz
rory_tomo36a_patch0_raw_split0_0000.nii.gz
rory_tomo36a_patch0_raw_v2_split0_0000.nii.gz
rory_tomo36b_patch0_raw_split0_0000.nii.gz
rory_tomo36b_patch0_raw_v2_split0_0000.nii.gz
rory_tomo37a_patch0_raw_split0_0000.nii.gz
rory_tomo37a_patch0_raw_v2_split0_0000.nii.gz


spinach_tomo03_patch000_raw_split0_0000.nii.gz
spinach_tomo03_patch000_split0_0000.nii.gz
spinach_tomo03_patch002_raw_split0_0000.nii.gz
spinach_tomo03_patch002_split0_0000.nii.gz
spinach_tomo03_patch004_raw_split0_0000.nii.gz
spinach_tomo03_patch004_split0_0000.nii.gz
spinach_tomo03_patch006_raw_split0_0000.nii.gz
spinach_tomo03_patch006_split0_0000.nii.gz
spinach_tomo03_patch008_raw_split0_0000.nii.gz
spinach_tomo03_patch008_split0_0000.nii.gz
spinach_tomo03_patch010_raw_split0_0000.nii.gz
spinach_tomo03_patch010_split0_0000.nii.gz
spinach_tomo03_patch020_raw_split0_0000.nii.gz
spinach_tomo03_patch020_split0_0000.nii.gz
spinach_tomo03_patch021_raw_split0_0000.nii.gz
spinach_tomo03_patch021_split0_0000.nii.gz
spinach_tomo03_patch022_raw_split0_0000.nii.gz
spinach_tomo03_patch022_split0_0000.nii.gz
spinach_tomo03_patch030_raw_split0_0000.nii.gz
spinach_tomo03_patch030_split0_0000.nii.gz
spinach_tomo03_patch031_raw_split0_0000.nii.gz
spinach_tomo03_patch031_split0_0000.nii.gz
spinach_tomo03_patch032_raw_split0_0000.nii.gz
spinach_tomo03_patch032_split0_0000.nii.gz
spinach_tomo32_patch000_split0_0000.nii.gz
spinach_tomo32_patch002_split0_0000.nii.gz
spinach_tomo32_patch004_split0_0000.nii.gz
spinach_tomo32_patch006_split0_0000.nii.gz
spinach_tomo32_patch008_split0_0000.nii.gz
spinach_tomo32_patch010_split0_0000.nii.gz
spinach_tomo32_patch012_split0_0000.nii.gz
spinach_tomo32_patch014_split0_0000.nii.gz
spinach_tomo32_patch020_split0_0000.nii.gz
spinach_tomo32_patch030_split0_0000.nii.gz
spinach_tomo32_patch031_split0_0000.nii.gz
spinach_tomo38_patch000_split0_0000.nii.gz
spinach_tomo38_patch002_split0_0000.nii.gz
spinach_tomo38_patch004_split0_0000.nii.gz
spinach_tomo38_patch006_split0_0000.nii.gz
spinach_tomo38_patch008_split0_0000.nii.gz
spinach_tomo38_patch010_split0_0000.nii.gz
spinach_tomo38_patch020_split0_0000.nii.gz
spinach_tomo38_patch021_split0_0000.nii.gz
spinach_tomo38_patch030_split0_0000.nii.gz

virly_cat2_00_split0_0000.nii.gz
virly_cat2_01_split0_0000.nii.gz
virly_cat2_02_split0_0000.nii.gz

