# exp setting
exp_name: memseg-v0
wandb_project_name: cryo-ttt-ttt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-v0-09606/epoch=184-val/dice_loss=0.37.ckpt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-v0-f321b/epoch=85-val/dice_loss=0.23.ckpt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-v0-97b27/epoch=182-val/dice_loss=0.75.ckpt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-v0-97b27/epoch=111-val/dice_loss=0.76.ckpt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-v0-f67f8/epoch=159-val/dice_loss=0.65.ckpt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-v0-f67f8/epoch=147-val/dice_loss=0.64.ckpt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-v0-1ec3f/epoch=179-val/dice_loss=0.65.ckpt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-dynunet-f2fd-chlamy-94d4d/epoch=520-val/dice_loss=0.48.ckpt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-dynunet-f2fd-chlamy-94d4d/epoch=543-val/dice_loss=0.46.ckpt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-dynunet-f2fd-chlamy-94d4d/epoch=608-val/dice_loss=0.44.ckpt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-dynunet-f2fd-chlamy-94d4d/epoch=678-val/dice_loss=0.43.ckpt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-dynunet-f2fd-chlamy-94d4d/epoch=820-val/dice_loss=0.40.ckpt
# ckpt_path: /workspaces/cryo/cryo-ttt/src/ttt_ckpt/memseg-dynunet-f2fd-chlamy-94d4d/epoch=797-val/dice_loss=0.38.ckpt
# ckpt_path: /mnt/hdd_pool_zion/userdata/diyor/ttt_ckpt/memseg-dynunet-f2fd-spinach-f2402/epoch=980-val/dice_loss=0.24.ckpt
# ckpt_path: /mnt/hdd_pool_zion/userdata/diyor/ttt_ckpt/memseg-dynunet-oracle-d7077/epoch=864-val/dice_loss=0.18.ckpt
ckpt_path: /mnt/hdd_pool_zion/userdata/diyor/ttt_ckpt/memseg-dynunet-oracle-masked-6b705/epoch=995-val/dice_loss=0.23.ckpt
seed: 42 # random seed
debug: False # debug mode, will use cpu only
devices: [ 0, 1 ] # gpu ids

# data related
profiler: null
strategy: ddp # if ddp, then disable shuffle
shuffle: False
test_load_num_workers: 32 # number of workers for loading data (8)
pin_memory: False
persistent_workers: False

accumulate_grad_batches: 1
gradient_clip_val: null

# (wandb) logging
check_val_every_n_epochs: 1
log_every_n_steps: 1
num_sanity_val_steps: 0
enable_progress_bar: True

defaults:
  - _self_
  - method: memdenoiseg
  # - method: denoiseg_f2fd
  # - method: denoiseg_v2
  # - method: deepict_unet3d_ittt