atty_YTC009_3_lam11_ts2_corrected_patch0_split0_0000.nii.gz
atty_YTC009_3_lam11_ts2_corrected_patch1_split0_0000.nii.gz
atty_YTC009_3_lam3_ts2_corrected_patch0_split0_0000.nii.gz


chlamy_165_patch10_raw_split0_0000.nii.gz
chlamy_165_patch10_split0_0000.nii.gz
chlamy_165_patch11_raw_split0_0000.nii.gz
chlamy_165_patch11_split0_0000.nii.gz
chlamy_172_patch0_split0_0000.nii.gz
chlamy_172_patch1_split0_0000.nii.gz
chlamy_17_patch0_split0_0000.nii.gz
chlamy_224_patch0_split0_0000.nii.gz
chlamy_224_patch1_split0_0000.nii.gz
chlamy_24_patch0_split0_0000.nii.gz
chlamy_24_patch10_raw_split0_0000.nii.gz
chlamy_24_patch10_split0_0000.nii.gz
chlamy_24_patch11_raw_split0_0000.nii.gz
chlamy_24_patch11_split0_0000.nii.gz
chlamy_24_patch12_raw_split0_0000.nii.gz
chlamy_24_patch12_split0_0000.nii.gz
chlamy_24_patch20_raw_split0_0000.nii.gz
chlamy_24_patch20_split0_0000.nii.gz
chlamy_24_patch21_raw_split0_0000.nii.gz
chlamy_24_patch21_split0_0000.nii.gz
chlamy_38_patch10_raw_split0_0000.nii.gz
chlamy_38_patch10_split0_0000.nii.gz
chlamy_38_patch11_raw_split0_0000.nii.gz
chlamy_38_patch11_split0_0000.nii.gz


cts_patch000_split0_0000.nii.gz
cts_patch001_split0_0000.nii.gz
cts_patch002_split0_0000.nii.gz
cts_patch003_split0_0000.nii.gz
cts_patch004_split0_0000.nii.gz
cts_patch005_split0_0000.nii.gz
cts_patch006_split0_0000.nii.gz
cts_patch007_split0_0000.nii.gz



deepict_TS_0004_patch0_raw_split0_0000.nii.gz


deepict_TS_026_patch0_raw_split0_0000.nii.gz
deepict_TS_026_patch1_raw_split0_0000.nii.gz
deepict_TS_030_patch0_raw_split0_0000.nii.gz


hdcr_6_patch0_split0_0000.nii.gz
hdcr_6_patch1_split0_0000.nii.gz


polnet_patch000_split0_0000.nii.gz
polnet_patch001_split0_0000.nii.gz
polnet_patch002_split0_0000.nii.gz
polnet_patch003_split0_0000.nii.gz
polnet_patch004_split0_0000.nii.gz
polnet_patch005_split0_0000.nii.gz
polnet_patch006_split0_0000.nii.gz
polnet_patch007_split0_0000.nii.gz



rory_tomo31a_patch0_raw_split0_0000.nii.gz
rory_tomo31a_patch0_raw_v2_split0_0000.nii.gz
rory_tomo33a_patch0_raw_split0_0000.nii.gz
rory_tomo33a_patch0_raw_v2_split0_0000.nii.gz
rory_tomo33b_patch0_raw_split0_0000.nii.gz
rory_tomo33b_patch0_raw_v2_split0_0000.nii.gz
rory_tomo34a_patch0_raw_split0_0000.nii.gz
rory_tomo34a_patch0_raw_v2_split0_0000.nii.gz



spinach_tomo02_patch000_raw_split0_0000.nii.gz
spinach_tomo02_patch000_split0_0000.nii.gz
spinach_tomo02_patch001_raw_split0_0000.nii.gz
spinach_tomo02_patch001_split0_0000.nii.gz
spinach_tomo02_patch002_raw_split0_0000.nii.gz
spinach_tomo02_patch002_split0_0000.nii.gz
spinach_tomo02_patch003_raw_split0_0000.nii.gz
spinach_tomo02_patch003_split0_0000.nii.gz
spinach_tomo02_patch004_raw_split0_0000.nii.gz
spinach_tomo02_patch004_split0_0000.nii.gz
spinach_tomo02_patch005_raw_split0_0000.nii.gz
spinach_tomo02_patch005_split0_0000.nii.gz
spinach_tomo02_patch006_raw_split0_0000.nii.gz
spinach_tomo02_patch006_split0_0000.nii.gz
spinach_tomo02_patch020_raw_split0_0000.nii.gz
spinach_tomo02_patch020_split0_0000.nii.gz
spinach_tomo02_patch021_raw_split0_0000.nii.gz
spinach_tomo02_patch021_split0_0000.nii.gz
spinach_tomo02_patch030_raw_split0_0000.nii.gz
spinach_tomo02_patch030_split0_0000.nii.gz
spinach_tomo04_patch000_split0_0000.nii.gz
spinach_tomo04_patch002_split0_0000.nii.gz
spinach_tomo04_patch004_split0_0000.nii.gz
spinach_tomo04_patch006_split0_0000.nii.gz
spinach_tomo04_patch008_split0_0000.nii.gz
spinach_tomo04_patch009_split0_0000.nii.gz
spinach_tomo04_patch020_split0_0000.nii.gz
spinach_tomo04_patch021_split0_0000.nii.gz
spinach_tomo04_patch030_split0_0000.nii.gz
spinach_tomo10_patch001_split0_0000.nii.gz
spinach_tomo10_patch002_split0_0000.nii.gz
spinach_tomo10_patch003_split0_0000.nii.gz
spinach_tomo10_patch009_split0_0000.nii.gz
spinach_tomo10_patch010_split0_0000.nii.gz
spinach_tomo10_patch011_split0_0000.nii.gz
spinach_tomo10_patch020_split0_0000.nii.gz
spinach_tomo10_patch030_split0_0000.nii.gz
spinach_tomo17_patch000_split0_0000.nii.gz
spinach_tomo17_patch001_split0_0000.nii.gz
spinach_tomo17_patch002_split0_0000.nii.gz
spinach_tomo17_patch006_split0_0000.nii.gz
spinach_tomo17_patch008_split0_0000.nii.gz
spinach_tomo17_patch009_split0_0000.nii.gz



virly_cat1_00_split0_0000.nii.gz
virly_cat1_01_split0_0000.nii.gz
virly_cat1_02_split0_0000.nii.gz
virly_cat1_03_split0_0000.nii.gz

# Validation set
atty_YTC009_3_lam3_ts2_corrected_patch1_split0_0000.nii.gz

chlamy_3_patch0_split0_0000.nii.gz
chlamy_441_patch0_raw_split0_0000.nii.gz
chlamy_441_patch0_split0_0000.nii.gz

cts_patch008_split0_0000.nii.gz
cts_patch009_split0_0000.nii.gz

deepict_TS_030_patch1_raw_split0_0000.nii.gz
deepict_TS_030_patch2_raw_split0_0000.nii.gz

polnet_patch008_split0_0000.nii.gz
polnet_patch009_split0_0000.nii.gz

rory_tomo34b_patch0_raw_split0_0000.nii.gz
rory_tomo34b_patch0_raw_v2_split0_0000.nii.gz

spinach_tomo17_patch010_split0_0000.nii.gz
spinach_tomo17_patch014_split0_0000.nii.gz
spinach_tomo17_patch015_split0_0000.nii.gz
spinach_tomo17_patch030_split0_0000.nii.gz