train_tomo_names:
  - atty_YTC009_3_lam11_ts2_corrected_patch0_split0_0000.nii.gz
  - atty_YTC009_3_lam11_ts2_corrected_patch1_split0_0000.nii.gz
  - atty_YTC009_3_lam3_ts2_corrected_patch0_split0_0000.nii.gz
  - atty_YTC009_3_lam3_ts2_corrected_patch1_split0_0000.nii.gz
  - atty_YTC009_3_lam7_ts2_corrected_patch0_split0_0000.nii.gz
  - atty_YTC009_3_lam7_ts2_corrected_patch1_split0_0000.nii.gz
  - atty_YTC009_3_lam8_ts2_corrected_patch0_split0_0000.nii.gz
  - atty_YTC009_3_lam8_ts2_corrected_patch1_split0_0000.nii.gz
  - chlamy_165_patch10_raw_split0_0000.nii.gz
  - chlamy_165_patch10_split0_0000.nii.gz
  - chlamy_165_patch11_raw_split0_0000.nii.gz
  - chlamy_165_patch11_split0_0000.nii.gz
  - chlamy_172_patch0_split0_0000.nii.gz
  - chlamy_172_patch1_split0_0000.nii.gz
  - chlamy_17_patch0_split0_0000.nii.gz
  - chlamy_224_patch0_split0_0000.nii.gz
  - chlamy_224_patch1_split0_0000.nii.gz
  - chlamy_24_patch0_split0_0000.nii.gz
  - chlamy_24_patch10_raw_split0_0000.nii.gz
  - chlamy_24_patch10_split0_0000.nii.gz
  - chlamy_24_patch11_raw_split0_0000.nii.gz
  - chlamy_24_patch11_split0_0000.nii.gz
  - chlamy_24_patch12_raw_split0_0000.nii.gz
  - chlamy_24_patch12_split0_0000.nii.gz
  - chlamy_24_patch20_raw_split0_0000.nii.gz
  - chlamy_24_patch20_split0_0000.nii.gz
  - chlamy_24_patch21_raw_split0_0000.nii.gz
  - chlamy_24_patch21_split0_0000.nii.gz
  - chlamy_38_patch10_raw_split0_0000.nii.gz
  - chlamy_38_patch10_split0_0000.nii.gz
  - chlamy_38_patch11_raw_split0_0000.nii.gz
  - chlamy_38_patch11_split0_0000.nii.gz
  - chlamy_3_patch0_split0_0000.nii.gz
  - chlamy_441_patch0_raw_split0_0000.nii.gz
  - chlamy_441_patch0_split0_0000.nii.gz
  - chlamy_50_patch20_split0_0000.nii.gz
  - chlamy_50_patch21_split0_0000.nii.gz
  - chlamy_54_patch0_raw_split0_0000.nii.gz
  - chlamy_54_patch0_split0_0000.nii.gz
  - chlamy_54_patch1_raw_split0_0000.nii.gz
  - chlamy_54_patch1_split0_0000.nii.gz
  - chlamy_54_patch2_raw_split0_0000.nii.gz
  - chlamy_54_patch2_split0_0000.nii.gz
  - chlamy_5_patch0_split0_0000.nii.gz
  - chlamy_633_patch10_raw_split0_0000.nii.gz
  - chlamy_633_patch10_split0_0000.nii.gz
  - chlamy_633_patch11_raw_split0_0000.nii.gz
  - chlamy_633_patch11_split0_0000.nii.gz
  - chlamy_633_patch12_raw_split0_0000.nii.gz
  - chlamy_633_patch12_split0_0000.nii.gz
  - chlamy_640_patch0_split0_0000.nii.gz
  - chlamy_640_patch1_split0_0000.nii.gz
  - chlamy_640_patch2_split0_0000.nii.gz
  - chlamy_6_patch0_split0_0000.nii.gz
  - chlamy_8_patch0_raw_split0_0000.nii.gz
  - chlamy_8_patch0_split0_0000.nii.gz
  - chlamy_8_patch1_raw_split0_0000.nii.gz
  - chlamy_8_patch1_split0_0000.nii.gz
  - chlamy_8_patch2_raw_split0_0000.nii.gz
  - chlamy_8_patch2_split0_0000.nii.gz
  - cts_patch000_split0_0000.nii.gz
  - cts_patch001_split0_0000.nii.gz
  - cts_patch002_split0_0000.nii.gz
  - cts_patch003_split0_0000.nii.gz
  - cts_patch004_split0_0000.nii.gz
  - cts_patch005_split0_0000.nii.gz
  - cts_patch006_split0_0000.nii.gz
  - cts_patch007_split0_0000.nii.gz
  - cts_patch008_split0_0000.nii.gz
  - cts_patch009_split0_0000.nii.gz
  - cts_patch010_split0_0000.nii.gz
  - cts_patch011_split0_0000.nii.gz
  - cts_patch012_split0_0000.nii.gz
  - cts_patch013_split0_0000.nii.gz
  - cts_patch014_split0_0000.nii.gz
  - cts_patch015_split0_0000.nii.gz
  - cts_patch016_split0_0000.nii.gz
  - cts_patch017_split0_0000.nii.gz
  - cts_patch018_split0_0000.nii.gz
  - cts_patch019_split0_0000.nii.gz
  - deepict_TS_0004_patch0_raw_split0_0000.nii.gz
  - deepict_TS_0007_patch0_raw_split0_0000.nii.gz
  - deepict_TS_0007_patch1_raw_split0_0000.nii.gz
  - deepict_TS_026_patch0_raw_split0_0000.nii.gz
  - deepict_TS_026_patch1_raw_split0_0000.nii.gz
  - deepict_TS_030_patch0_raw_split0_0000.nii.gz
  - deepict_TS_030_patch1_raw_split0_0000.nii.gz
  - deepict_TS_030_patch2_raw_split0_0000.nii.gz
  - deepict_TS_034_patch0_raw_split0_0000.nii.gz
  - deepict_TS_034_patch1_raw_split0_0000.nii.gz
  - deepict_TS_034_patch2_raw_split0_0000.nii.gz
  - deepict_TS_034_patch3_raw_split0_0000.nii.gz
  - deepict_TS_041_patch0_raw_split0_0000.nii.gz
  - deepict_TS_041_patch1_raw_split0_0000.nii.gz
  - deepict_TS_041_patch2_raw_split0_0000.nii.gz
  - hdcr_6_patch0_split0_0000.nii.gz
  - hdcr_6_patch1_split0_0000.nii.gz
  - hdcr_9_patch0_split0_0000.nii.gz
  - polnet_patch000_split0_0000.nii.gz
  - polnet_patch001_split0_0000.nii.gz
  - polnet_patch002_split0_0000.nii.gz
  - polnet_patch003_split0_0000.nii.gz
  - polnet_patch004_split0_0000.nii.gz
  - polnet_patch005_split0_0000.nii.gz
  - polnet_patch006_split0_0000.nii.gz
  - polnet_patch007_split0_0000.nii.gz
  - polnet_patch008_split0_0000.nii.gz
  - polnet_patch009_split0_0000.nii.gz
  - polnet_patch010_split0_0000.nii.gz
  - polnet_patch011_split0_0000.nii.gz
  - polnet_patch012_split0_0000.nii.gz
  - polnet_patch013_split0_0000.nii.gz
  - polnet_patch014_split0_0000.nii.gz
  - polnet_patch015_split0_0000.nii.gz
  - polnet_patch016_split0_0000.nii.gz
  - polnet_patch017_split0_0000.nii.gz
  - polnet_patch018_split0_0000.nii.gz
  - polnet_patch019_split0_0000.nii.gz
  - rory_tomo31a_patch0_raw_split0_0000.nii.gz
  - rory_tomo31a_patch0_raw_v2_split0_0000.nii.gz
  - rory_tomo33a_patch0_raw_split0_0000.nii.gz
  - rory_tomo33a_patch0_raw_v2_split0_0000.nii.gz
  - rory_tomo33b_patch0_raw_split0_0000.nii.gz
  - rory_tomo33b_patch0_raw_v2_split0_0000.nii.gz
  - rory_tomo34a_patch0_raw_split0_0000.nii.gz
  - rory_tomo34a_patch0_raw_v2_split0_0000.nii.gz
  - rory_tomo34b_patch0_raw_split0_0000.nii.gz
  - rory_tomo34b_patch0_raw_v2_split0_0000.nii.gz
  - rory_tomo35a_patch0_raw_split0_0000.nii.gz
  - rory_tomo35a_patch0_raw_v2_split0_0000.nii.gz
  - rory_tomo35b_patch0_raw_split0_0000.nii.gz
  - rory_tomo35b_patch0_raw_v2_split0_0000.nii.gz
  - rory_tomo36a_patch0_raw_split0_0000.nii.gz
  - rory_tomo36a_patch0_raw_v2_split0_0000.nii.gz
  - rory_tomo36b_patch0_raw_split0_0000.nii.gz
  - rory_tomo36b_patch0_raw_v2_split0_0000.nii.gz
  - rory_tomo37a_patch0_raw_split0_0000.nii.gz
  - rory_tomo37a_patch0_raw_v2_split0_0000.nii.gz
  - virly_cat1_00_split0_0000.nii.gz
  - virly_cat1_01_split0_0000.nii.gz
  - virly_cat1_02_split0_0000.nii.gz
  - virly_cat1_03_split0_0000.nii.gz
  - virly_cat2_00_split0_0000.nii.gz
  - virly_cat2_01_split0_0000.nii.gz
  - virly_cat2_02_split0_0000.nii.gz